# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          whatamelon
baseurl:        "https://whatamelon.github.io/"
url:            "https://whatamelon.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         whatamelon
  url:          https://whatamelon.github.io/
  email:        hsh0617@naver.com
  github:       whatamelon

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/whatamelon/whatamelon.github.io
